### PR TITLE
feat: update repo

### LINKED ISSUE #1: the word "a" seems to not show up in the list of words created in 2015.
Does the script discard single letter words? "a" is definitely a word. Luckily this actually has no bearing on what i need the word frequencies for, but you may want to consider that if you plan to use your script.

On a separate note, this little tool saved me a ton of trouble, so thanks for sharing it on github. I don't even need the tool itself seeing as you provided a sample. :+1:

### PR DESCRIPTION
**Pull request by borisdayma**
This PR provides the following changes:

- make script compatible with latest `wikiextractor` (remove submodule and install as dependency)
- handle single letter words (fix #1)
- update results

### CODE REVIEW

**Comment by borisdayma** [comment]
Great job with this repo!
I could not make it work without these updates. Maybe it was supposed to work with python 2?
Anyway the latest wikiextractor is pretty fast using several processes.

**Comment by IlyaSemenov** [comment]
Thank you for this update. Most of what you've done makes sense, I appreciate keeping this mini project up to date. I have two concerns:

1) Not pinning particular versions of dependencies is a time bomb. Since you replaced git submodule (which was pointing to a specific commit) with a pip dependency, please pin it. I suggest to use `pip-tools` to generate `requirements.txt`. Actually, I would have done that myself, but:

2) I cloned your repo, installed the dependencies, downloaded `etwiki` data (not `enwiki` for simplicity), and here's what I got:

```
wiki-ext ❯ ./gather_wordfreq.py dumps.wikimedia.org/etwiki/latest/*.bz2>1.txt
Processing dumps.wikimedia.org/etwiki/latest/etwiki-latest-pages-articles.xml.bz2
INFO: Starting page extraction from dumps.wikimedia.org/etwiki/latest/etwiki-latest-pages-articles.xml.bz2.
Traceback (most recent call last):
  File "/Users/semenov/.pyenv/versions/wiki-ext/bin/wikiextractor", line 8, in <module>
    sys.exit(main())
  File "/Users/semenov/.pyenv/versions/3.8.7/envs/wiki-ext/lib/python3.8/site-packages/wikiextractor/WikiExtractor.py", line 616, in main
    process_dump(input_file, args.templates, output_path, file_size,
  File "/Users/semenov/.pyenv/versions/3.8.7/envs/wiki-ext/lib/python3.8/site-packages/wikiextractor/WikiExtractor.py", line 357, in process_dump
    reduce.start()
  File "/Users/semenov/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/semenov/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/semenov/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/semenov/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/semenov/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/semenov/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/semenov/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
```

Thoughts?

**Comment by borisdayma** [comment]
I tested it with your same python version (3.8.7) and pinned the version and it worked fine.

What environment are you using (in case it still does not work)?

**Comment by IlyaSemenov** [comment]
This could have something to do with me running it on M1 (arm64) not on x86 like before. I'll test it on Linux and merge.

**Comment by RABijl** [comment]
is there an update on the status of this pr?

**Comment by IlyaSemenov** [comment]
@borisdayma Thank you again for the PR.

@RABijl Thank you for bringing this up. I've just merged the PR.

**Pull request merged**
